title: Esther's Data Projects
description: Data Science | SQL | Power BI | Analytics
logo: assets/images/myphoto.jpg
show_downloads: True
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
